FROM ubuntu:22.10
ENV DEBIAN_FRONTEND=noninteractive 
RUN apt-get update  && apt install -y 
RUN apt-get install -y curl
RUN apt-get install -y wget
RUN apt-get upgrade -y
RUN apt-get install -y dotnet-sdk-6.0
RUN apt-get update;
RUN apt-get install -y apt-transport-https  
RUN apt-get update  
RUN apt-get install -y git-all
RUN apt-get update && apt-get install -y libgdiplus
RUN apt-get install -y apache2
